# Generated by Django 4.1.7 on 2023-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_post_edited_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.CharField(choices=[('OOO', 'Test'), ('TAR', 'Escape From Tarkov')], default='Test', max_length=3),
        ),
    ]
